# -*- coding: utf-8 -*-
"""cleaning_wiki.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hTuEqIJ8YSKlQlJ6B-NaJGYxaZwukFMd
"""

import os
import re


def clean_wiki(text):
    text = re.sub(r'\n', '', text)  # Remove newline characters
    text = re.sub(r'\t', '', text)  # Remove tab characters
    text = re.sub(r'\([^)]*\)', '', text)  # Remove between ()
    text = re.sub(r'==\s*İstinadlar\s*==[\s\S]*', '', text)  # Remove everything after headline
    text = re.sub(r'==\s*Həmçinin bax\s*==[\s\S]*', '', text)
    text = re.sub(r'==\s*Qalereya\s*==[\s\S]*', '', text)
    text = re.sub(r'==\s*Mənbə\s*==[\s\S]*', '', text)
    text = re.sub(r'==\s*Tanınmış işləri\s*==[\s\S]*', '', text)
    text = re.sub(r'==.*?==', '', text)  # Remove everthing between ==
    text = re.sub(r'\/[^\/]*\/', '', text)  # Remove between //
    text = re.sub(r'Fayl:[^.]*\.', '', text)  # Remove descriptive words
    text = re.sub(r'Şəkil:[^.]*\.', '', text)
    text = re.sub(r'Misallar[^.]*\.', '', text)
    text = re.sub(r'[^a-zA-Z0-9\sƏəŞşÇçĞğÖöIıÜüİi,.?!:;\-]+', '', text)  # Remove everything except alnum
    text = re.sub(r'<.*?>', '', text)  # Remove between <>
    text = re.sub(r'https?:\/\/\S+', '', text)  # Remove all the links
    text = re.sub(r' +', ' ', text)  # Remove multiple space with single

    return text


pattern = r"''\w+''\s+''\w+''"
# path to the folder containing the text files
folder_path = "/content/sample_data/articles"
# path to the folder to save the cleaned files
output_folder_path = "/content/sample_data/articles_cleaned"

# create the output folder if it doesn't exist
if not os.path.exists(output_folder_path):
    os.makedirs(output_folder_path)

# iterate through all the text files in the folder
for file_name in os.listdir(folder_path):
    # check if the file is a text file
    if file_name.endswith(".txt"):
        # read the contents of the file
        with open(os.path.join(folder_path, file_name), "r") as f:
            text = f.read()

        # check if the file matches the regex pattern
        if not (re.search(pattern, text) or "**" in text):
            # if the file does not match the pattern, clean the text
            cleaned_text = clean_wiki(text)

            # write the cleaned text back to the file
            if "." in cleaned_text:
                with open(os.path.join(output_folder_path, file_name), "w") as f:
                    print(cleaned_text)
                    f.write(cleaned_text)
        else:
            # if the file does not match any of the conditions, skip it
            continue
